// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqDxKoUbwv4RPX4L42HARNPV_WST_gA4',
    appId: '1:18016621742:web:ecb7c57d0dbc9cc604493f',
    messagingSenderId: '18016621742',
    projectId: 'azamov-second-me',
    authDomain: 'azamov-second-me.firebaseapp.com',
    storageBucket: 'azamov-second-me.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHVjNF9pK-TdYJdXGvaw2VUmOAIEf5QGY',
    appId: '1:18016621742:android:d5de3bb7a74f7c8104493f',
    messagingSenderId: '18016621742',
    projectId: 'azamov-second-me',
    storageBucket: 'azamov-second-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQe1_jPkkHAopX7HIPb8KrLnWUdiahp0',
    appId: '1:18016621742:ios:4df8f83a7eef866704493f',
    messagingSenderId: '18016621742',
    projectId: 'azamov-second-me',
    storageBucket: 'azamov-second-me.firebasestorage.app',
    iosClientId: '18016621742-3m2g1tn7n1t6dfp59lnafhungih3mgqq.apps.googleusercontent.com',
    iosBundleId: 'uz.azamov.azamovSecondMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQe1_jPkkHAopX7HIPb8KrLnWUdiahp0',
    appId: '1:18016621742:ios:4df8f83a7eef866704493f',
    messagingSenderId: '18016621742',
    projectId: 'azamov-second-me',
    storageBucket: 'azamov-second-me.firebasestorage.app',
    iosClientId: '18016621742-3m2g1tn7n1t6dfp59lnafhungih3mgqq.apps.googleusercontent.com',
    iosBundleId: 'uz.azamov.azamovSecondMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrqDxKoUbwv4RPX4L42HARNPV_WST_gA4',
    appId: '1:18016621742:web:bd2b93912efee91604493f',
    messagingSenderId: '18016621742',
    projectId: 'azamov-second-me',
    authDomain: 'azamov-second-me.firebaseapp.com',
    storageBucket: 'azamov-second-me.firebasestorage.app',
  );
}
